/**
 * seed-events.js — Inserta/actualiza eventos híbridos en Supabase
 * Fuentes: hybridleague.es, gijonthrowdown.es, thebattle.es, theboxinthebox.com,
 *          calendariocarrerasobstaculos.es, farinatorace.es, rafanadalclub.com,
 *          thehybridgames.fit, hybridzone.es, wezone.es, survivor-race.com
 *
 * Uso: node scripts/seed-events.js
 * Requiere: SUPABASE_URL y SUPABASE_SERVICE_KEY en .env.local
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Leer .env.local ──────────────────────────────────────────────────────────
function loadEnv() {
  const envPath = resolve(__dirname, '..', '.env.local');
  try {
    const content = readFileSync(envPath, 'utf8');
    for (const line of content.split('\n')) {
      const [key, ...rest] = line.split('=');
      if (key && rest.length) process.env[key.trim()] = rest.join('=').trim();
    }
  } catch {
    console.warn('⚠  .env.local no encontrado, usando variables de entorno del sistema.');
  }
}
loadEnv();

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://ssyljhtganuaanczxeep.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_SERVICE_KEY) {
  console.error('❌  Falta SUPABASE_SERVICE_KEY en .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// ── Datos de eventos ─────────────────────────────────────────────────────────
// Campos: nombre, fecha, fecha_iso, ubicacion, municipio, provincia, comunidad,
//         pais, modalidad, modalidad_id, modalidad_parent, distancia, precio,
//         estado, url, formato, notas, source

const EVENTS = [
  // ═══════════════════════════════════════════════════════════
  // HYBRIDLEAGUE.ES
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'Hybrid League — Ronda 4 Octubre 2026',
    fecha: '3 Oct 2026',
    fecha_iso: '2026-10-03',
    ubicacion: 'Pinto, Madrid',
    municipio: 'Pinto',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-fitness',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: '41 € / persona (parejas)',
    estado: 'Abierta',
    url: 'https://hybridleague.es/evento/entradas-dobles-pro-o-amateur-abril-03-10-2026-2/',
    formato: 'Parejas',
    notas: 'Categorías Amateur (82€ pareja) y Pro (96€ pareja)',
    source: 'hybridleague.es',
  },
  {
    nombre: 'Hybrid League — Ronda Febrero 2026',
    fecha: '21 Feb 2026',
    fecha_iso: '2026-02-21',
    ubicacion: 'Pinto, Madrid',
    municipio: 'Pinto',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-fitness',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Cerrada',
    url: 'https://hybridleague.es/inscripcion/',
    formato: 'Parejas',
    notas: 'SOLD OUT. Evento en PositiveEnergy.',
    source: 'hybridleague.es',
  },

  // ═══════════════════════════════════════════════════════════
  // GIJONTHROWDOWN.ES
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'Gijón Throwdown 2026',
    fecha: '26 Sep 2026',
    fecha_iso: '2026-09-26',
    ubicacion: 'Gijón, Asturias',
    municipio: 'Gijón',
    provincia: 'Asturias',
    comunidad: 'Principado de Asturias',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://arena.wodbuster.com/competition.aspx?id=4072',
    formato: 'Equipos',
    notas: 'Equipos de 4 (MMMF). Categorías GOLD/SILVER/BRONZE. Premio 1.000€.',
    source: 'gijonthrowdown.es',
  },

  // ═══════════════════════════════════════════════════════════
  // THEBATTLE.ES
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'The Battle Games X Edition 2026',
    fecha: '24 Abr 2026',
    fecha_iso: '2026-04-24',
    ubicacion: 'Castellón de la Plana, Castellón',
    municipio: 'Castellón de la Plana',
    provincia: 'Castellón',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: '40 € (online) / 70–110 € (presencial)',
    estado: 'Abierta',
    url: 'https://arena.wodbuster.com/register.aspx?id=3192',
    formato: 'Individual',
    notas: 'Décima edición. Clasificatoria online + final presencial 24-26 Abr.',
    source: 'thebattle.es',
  },

  // ═══════════════════════════════════════════════════════════
  // THEBOXINTHEBOX.COM
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'Valencia Throwdown 2026',
    fecha: '5 Jun 2026',
    fecha_iso: '2026-06-05',
    ubicacion: 'La Eliana, Valencia',
    municipio: 'La Eliana',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/valencia-throwdown-2026/',
    formato: 'Individual',
    notas: 'Individual, parejas y tríos. RX, Intermedio, Scaled, Master.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Ibiza WOD Island 2026',
    fecha: '29 May 2026',
    fecha_iso: '2026-05-29',
    ubicacion: 'Ibiza, Islas Baleares',
    municipio: 'Ibiza',
    provincia: 'Islas Baleares',
    comunidad: 'Islas Baleares',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Próximamente',
    url: 'https://theboxinthebox.com/event/ibiza-wod-island-2026/',
    formato: 'Individual',
    notas: 'Individual y equipos. Categorías Teen, Beginner, Intermedio, RX, Master.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'MURPH VALENCIA 2026 — Pay the Man',
    fecha: '23 May 2026',
    fecha_iso: '2026-05-23',
    ubicacion: 'Valencia',
    municipio: 'Valencia',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-fitness',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://murphvalencia.org/MURPH-VALENCIA',
    formato: 'Individual',
    notas: 'Con Josh Bridges (ex-Navy SEAL). RX, Intermedio, Scaled, Experience.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Fungo Race 2026',
    fecha: '12 Abr 2026',
    fecha_iso: '2026-04-12',
    ubicacion: 'El Puerto de Santa María, Cádiz',
    municipio: 'El Puerto de Santa María',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/fungo-2026-el-ano-del-trifungo/',
    formato: null,
    notas: 'TriFungo: Fungo Race + Fungo Hybrid + Fungo Urban.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Strong Race Otoño 2026',
    fecha: '7 Nov 2026',
    fecha_iso: '2026-11-07',
    ubicacion: 'Mallorca, Islas Baleares',
    municipio: 'Mallorca',
    provincia: 'Islas Baleares',
    comunidad: 'Islas Baleares',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Próximamente',
    url: 'https://theboxinthebox.com/event/strong-race-otono-2026/',
    formato: 'Parejas',
    notas: 'Formato HYROX-like. 10 estaciones + 500m. Tanda élite.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'DEKA Barcelona 2026',
    fecha: '26 Sep 2026',
    fecha_iso: '2026-09-26',
    ubicacion: 'Barcelona',
    municipio: 'Barcelona',
    provincia: 'Barcelona',
    comunidad: 'Cataluña',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '5 km',
    precio: null,
    estado: 'Próximamente',
    url: 'https://es.spartan.com/es/races/deka-barcelona',
    formato: 'Individual',
    notas: 'DEKA FIT (~5km), DEKA MILE, DEKA STRONG. Individual y equipos.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Tomelloso Throwdown 2026',
    fecha: '9 May 2026',
    fecha_iso: '2026-05-09',
    ubicacion: 'Tomelloso, Ciudad Real',
    municipio: 'Tomelloso',
    provincia: 'Ciudad Real',
    comunidad: 'Castilla-La Mancha',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/tomelloso-throwdown-2026/',
    formato: 'Parejas',
    notas: 'Parejas MM/MF/FF. Categoría Adaptive (individual).',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'La Batalla de Guisando 2026',
    fecha: '22 May 2026',
    fecha_iso: '2026-05-22',
    ubicacion: 'El Tiemblo, Ávila',
    municipio: 'El Tiemblo',
    provincia: 'Ávila',
    comunidad: 'Castilla y León',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/la-batalla-de-guisando-2026/',
    formato: 'Equipos',
    notas: 'Cross Training por equipos. RX e Intermedio. MHHH y MMHH.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'MAD Fitness Festival 2026',
    fecha: '29 May 2026',
    fecha_iso: '2026-05-29',
    ubicacion: 'Ciudad Real',
    municipio: 'Ciudad Real',
    provincia: 'Ciudad Real',
    comunidad: 'Castilla-La Mancha',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/mad-fitness-festival-2026/',
    formato: 'Individual',
    notas: 'Qualifying oficial CrossFit Games. Individual y Equipos. Master +35.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'O2 Limit Challenge 2026',
    fecha: '10 Jul 2026',
    fecha_iso: '2026-07-10',
    ubicacion: 'Sierra Nevada, Granada',
    municipio: 'Sierra Nevada',
    provincia: 'Granada',
    comunidad: 'Andalucía',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/o2-limit-challenge-2026/',
    formato: 'Equipos',
    notas: 'Equipos de 3 (RX/Masters), equipos de 4 (Intermedio/Scaled). Individual RX.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Sacaba Summer Games 2026',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'Málaga',
    municipio: 'Málaga',
    provincia: 'Málaga',
    comunidad: 'Andalucía',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://www.sacabasummergames.com/',
    formato: 'Parejas',
    notas: 'Playa de la Misericordia. Categorías Scaled, Intermedio, RX, Master.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Villanueva Throwdown 2026',
    fecha: '20 Jun 2026',
    fecha_iso: '2026-06-20',
    ubicacion: 'Villanueva de la Cañada, Madrid',
    municipio: 'Villanueva de la Cañada',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Próximamente',
    url: 'https://theboxinthebox.com/event/villanueva-throwdown-2026/',
    formato: 'Parejas',
    notas: 'Parejas MM/FF/MF. Categorías RX, Intermedio, Scaled.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Ablitas Team Battle 2026',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'Ablitas, Navarra',
    municipio: 'Ablitas',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://ablitasteamsbattle.com/',
    formato: 'Equipos',
    notas: 'Quinta edición. Equipos de 4 (3H+1M). RX e Intermedio. 5 WODs.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Poseidon Race 2026',
    fecha: '16 May 2026',
    fecha_iso: '2026-05-16',
    ubicacion: 'Cerceda, A Coruña',
    municipio: 'Cerceda',
    provincia: 'A Coruña',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/poseidon-race-2026/',
    formato: null,
    notas: null,
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Ibi Strength Showdown 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'Ibi, Alicante',
    municipio: 'Ibi',
    provincia: 'Alicante',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/ibi-strength-showdown-2026/',
    formato: null,
    notas: null,
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Consuegra Throwdown 2026',
    fecha: '20 Jun 2026',
    fecha_iso: '2026-06-20',
    ubicacion: 'Consuegra, Toledo',
    municipio: 'Consuegra',
    provincia: 'Toledo',
    comunidad: 'Castilla-La Mancha',
    modalidad: 'CrossFit',
    modalidad_id: 'func-crossfit',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://theboxinthebox.com/event/consuegra-throwdown-2026-la-batalla-del-verano/',
    formato: null,
    notas: null,
    source: 'theboxinthebox.com',
  },

  // ═══════════════════════════════════════════════════════════
  // FARINATORACE.ES
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'Farinato Race León 2026',
    fecha: '2 May 2026',
    fecha_iso: '2026-05-02',
    ubicacion: 'León',
    municipio: 'León',
    provincia: 'León',
    comunidad: 'Castilla y León',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: '3–7 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://inscripciones.tucrono.com/inscripcion/farinato-race-leon-2026/',
    formato: 'Individual',
    notas: 'Modalidades: Iniciación 3km, Élite 7km, Equipos, Family, Inclusiva, Farinatitos.',
    source: 'farinatorace.es',
  },
  {
    nombre: 'Farinato Race Alcobendas 2026',
    fecha: '16 May 2026',
    fecha_iso: '2026-05-16',
    ubicacion: 'Alcobendas, Madrid',
    municipio: 'Alcobendas',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: '3–7 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://inscripciones.tucrono.com/inscripcion/farinato-race-alcobendas-2026/',
    formato: 'Individual',
    notas: 'Iniciación 3km, Élite 7km, Equipos, Family, Farinatitos.',
    source: 'farinatorace.es',
  },
  {
    nombre: 'Farinato Hybrid Medina del Campo 2026',
    fecha: '23 May 2026',
    fecha_iso: '2026-05-23',
    ubicacion: 'Medina del Campo, Valladolid',
    municipio: 'Medina del Campo',
    provincia: 'Valladolid',
    comunidad: 'Castilla y León',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://inscripciones.tucrono.com/inscripcion/farinato-hibrid-medina-del-campo/',
    formato: 'Individual',
    notas: 'Élite Pro, Age Group, Open (Tribe), Farinato Team. Formato HYROX-like.',
    source: 'farinatorace.es',
  },
  {
    nombre: 'Farinato Race Gijón 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'Gijón, Asturias',
    municipio: 'Gijón',
    provincia: 'Asturias',
    comunidad: 'Principado de Asturias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: '3–7 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://inscripciones.tucrono.com/inscripcion/farinato-race-gijon-2026/',
    formato: 'Individual',
    notas: 'Iniciación 3km, Sprint Élite 3km, Élite 7km, Equipos, Family.',
    source: 'farinatorace.es',
  },

  // ═══════════════════════════════════════════════════════════
  // RAFANADALCLUB.COM
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'RNC Hybrid Race 1ª Edición',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'Manacor, Mallorca',
    municipio: 'Manacor',
    provincia: 'Islas Baleares',
    comunidad: 'Islas Baleares',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '500 m / vuelta',
    precio: '90 € / pareja (early bird)',
    estado: 'Abierta',
    url: 'https://www.elitechip.net/index.php?zwshow=compdet&idcomp=7380225',
    formato: 'Parejas',
    notas: 'Rafa Nadal Club. 7 estaciones funcionales. Adultos y categoría Juvenil.',
    source: 'rafanadalclub.com',
  },

  // ═══════════════════════════════════════════════════════════
  // THEHYBRIDGAMES.FIT
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'The Hybrid Games 3ª Edición Valencia',
    fecha: '25 Abr 2026',
    fecha_iso: '2026-04-25',
    ubicacion: 'Valencia',
    municipio: 'Valencia',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-fitness',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: '75 € (individual) / 140 € (parejas) / 200 € (equipos)',
    estado: 'Cerrada',
    url: 'https://thehybridgames.fit/hybrid-games-3a-edicion-valencia/',
    formato: 'Individual',
    notas: 'Velódromo Lluis Puig. SOLD OUT. Hybrid Total + WOD Sorpresa.',
    source: 'thehybridgames.fit',
  },

  // ═══════════════════════════════════════════════════════════
  // HYBRIDZONE.ES
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'HybridZone 2026',
    fecha: null,
    fecha_iso: null,
    ubicacion: 'Cantabria',
    municipio: null,
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-fitness',
    modalidad_parent: 'funcional',
    distancia: null,
    precio: null,
    estado: 'Próximamente',
    url: 'https://hybridzone.es/',
    formato: null,
    notas: 'Primera Competición Híbrida Indoor de Cantabria.',
    source: 'hybridzone.es',
  },

  // ═══════════════════════════════════════════════════════════
  // WEZONE.ES / HYBRID DAY
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'Hybrid Day Madrid 2026',
    fecha: null,
    fecha_iso: null,
    ubicacion: 'Madrid',
    municipio: 'Madrid',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '8 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://www.tickettailor.com/events/hybridday/1908352',
    formato: 'Individual',
    notas: '8km running + 8 estaciones funcionales. Liga Ibérica.',
    source: 'wezone.es',
  },
  {
    nombre: 'Hybrid Day Valencia 2026',
    fecha: null,
    fecha_iso: null,
    ubicacion: 'Valencia',
    municipio: 'Valencia',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '8 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://www.tickettailor.com/events/hybridday/1910316',
    formato: 'Individual',
    notas: '8km running + 8 estaciones funcionales. Liga Ibérica.',
    source: 'wezone.es',
  },
  {
    nombre: 'Hybrid Day Sevilla 2026',
    fecha: null,
    fecha_iso: null,
    ubicacion: 'Sevilla',
    municipio: 'Sevilla',
    provincia: 'Sevilla',
    comunidad: 'Andalucía',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '8 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://www.wezone.es/blog/hybrid-day-la-nueva-frontera-del-fitness/',
    formato: 'Individual',
    notas: '8km running + 8 estaciones funcionales. Liga Ibérica.',
    source: 'wezone.es',
  },
  {
    nombre: 'Hybrid Day Málaga 2026',
    fecha: null,
    fecha_iso: null,
    ubicacion: 'Málaga',
    municipio: 'Málaga',
    provincia: 'Málaga',
    comunidad: 'Andalucía',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '8 km',
    precio: null,
    estado: 'Abierta',
    url: 'https://www.tickettailor.com/events/hybridday/1913262',
    formato: 'Individual',
    notas: '8km running + 8 estaciones funcionales. Liga Ibérica.',
    source: 'wezone.es',
  },

  // ═══════════════════════════════════════════════════════════
  // LIGA HÍBRIDA ANDALUCÍA (theboxinthebox.com)
  // ═══════════════════════════════════════════════════════════
  {
    nombre: 'Liga Híbrida Andalucía 2026 — Sevilla',
    fecha: '7 Mar 2026',
    fecha_iso: '2026-03-07',
    ubicacion: 'Sevilla',
    municipio: 'Sevilla',
    provincia: 'Sevilla',
    comunidad: 'Andalucía',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '700 m / estación',
    precio: null,
    estado: 'Abierta',
    url: 'https://www.ligahibridaandalucia.com/',
    formato: 'Individual',
    notas: 'Running + fitness funcional. Liga con 4 sedes. +20.000€ en premios.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Liga Híbrida Andalucía 2026 — Málaga',
    fecha: '16 May 2026',
    fecha_iso: '2026-05-16',
    ubicacion: 'Málaga',
    municipio: 'Málaga',
    provincia: 'Málaga',
    comunidad: 'Andalucía',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '700 m / estación',
    precio: null,
    estado: 'Abierta',
    url: 'https://www.ligahibridaandalucia.com/',
    formato: 'Individual',
    notas: 'Running + fitness funcional. Liga con 4 sedes.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Liga Híbrida Andalucía 2026 — Córdoba',
    fecha: '26 Sep 2026',
    fecha_iso: '2026-09-26',
    ubicacion: 'Córdoba',
    municipio: 'Córdoba',
    provincia: 'Córdoba',
    comunidad: 'Andalucía',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '700 m / estación',
    precio: null,
    estado: 'Próximamente',
    url: 'https://www.ligahibridaandalucia.com/',
    formato: 'Individual',
    notas: 'Running + fitness funcional. Liga con 4 sedes.',
    source: 'theboxinthebox.com',
  },
  {
    nombre: 'Liga Híbrida Andalucía 2026 — Jaén',
    fecha: '24 Oct 2026',
    fecha_iso: '2026-10-24',
    ubicacion: 'Jaén',
    municipio: 'Jaén',
    provincia: 'Jaén',
    comunidad: 'Andalucía',
    modalidad: 'Functional Fitness',
    modalidad_id: 'func-hyrox',
    modalidad_parent: 'funcional',
    distancia: '700 m / estación',
    precio: null,
    estado: 'Próximamente',
    url: 'https://www.ligahibridaandalucia.com/',
    formato: 'Individual',
    notas: 'Running + fitness funcional. Liga con 4 sedes.',
    source: 'theboxinthebox.com',
  },

  // ═══════════════════════════════════════════════════════════
  // CALENDARIOCARRERASOBSTACULOS.ES — ABRIL 2026
  // ═══════════════════════════════════════════════════════════
  {
    nombre: "Gladiator's Day 2026",
    fecha: '11 Abr 2026',
    fecha_iso: '2026-04-11',
    ubicacion: 'Artajona, Navarra',
    municipio: 'Artajona',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Survivor Race Alicante 2026',
    fecha: '11 Abr 2026',
    fecha_iso: '2026-04-11',
    ubicacion: 'Alicante',
    municipio: 'Alicante',
    provincia: 'Alicante',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://survivor-race.com/carreras/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'OCR Mencey Granadilla 2026',
    fecha: '12 Abr 2026',
    fecha_iso: '2026-04-12',
    ubicacion: 'Granadilla de Abona, Tenerife',
    municipio: 'Granadilla de Abona',
    provincia: 'Santa Cruz de Tenerife',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Milex Race Beniel 2026',
    fecha: '18 Abr 2026',
    fecha_iso: '2026-04-18',
    ubicacion: 'Beniel, Murcia',
    municipio: 'Beniel',
    provincia: 'Murcia',
    comunidad: 'Región de Murcia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Medieval Xtreme Race Torreblanca 2026',
    fecha: '19 Abr 2026',
    fecha_iso: '2026-04-19',
    ubicacion: 'Torreblanca, Castellón',
    municipio: 'Torreblanca',
    provincia: 'Castellón',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Alma Guerrera 2026',
    fecha: '19 Abr 2026',
    fecha_iso: '2026-04-19',
    ubicacion: 'Castañeda, Cantabria',
    municipio: 'Castañeda',
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío de Guerreros Gernika 2026',
    fecha: '19 Abr 2026',
    fecha_iso: '2026-04-19',
    ubicacion: 'Gernika-Lumo, Bizkaia',
    municipio: 'Gernika-Lumo',
    provincia: 'Bizkaia',
    comunidad: 'País Vasco',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Bull Race Quel 2026',
    fecha: '25 Abr 2026',
    fecha_iso: '2026-04-25',
    ubicacion: 'Quel, La Rioja',
    municipio: 'Quel',
    provincia: 'La Rioja',
    comunidad: 'La Rioja',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'La Batalla de las Sardinas 2026',
    fecha: '25 Abr 2026',
    fecha_iso: '2026-04-25',
    ubicacion: 'Candás, Asturias',
    municipio: 'Candás',
    provincia: 'Asturias',
    comunidad: 'Principado de Asturias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Pretorian Race Sarria 2026',
    fecha: '25 Abr 2026',
    fecha_iso: '2026-04-25',
    ubicacion: 'Sarria, Lugo',
    municipio: 'Sarria',
    provincia: 'Lugo',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Berserker Xtreme Race Tacoronte 2026',
    fecha: '26 Abr 2026',
    fecha_iso: '2026-04-26',
    ubicacion: 'Tacoronte, Tenerife',
    municipio: 'Tacoronte',
    provincia: 'Santa Cruz de Tenerife',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Adrenaline Race Almuñécar 2026',
    fecha: '26 Abr 2026',
    fecha_iso: '2026-04-26',
    ubicacion: 'Almuñécar, Granada',
    municipio: 'Almuñécar',
    provincia: 'Granada',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── MAYO 2026 ──────────────────────────────────────────────
  {
    nombre: 'Desafío Sierra de Cádiz 2026',
    fecha: '2 May 2026',
    fecha_iso: '2026-05-02',
    ubicacion: 'Arcos de la Frontera, Cádiz',
    municipio: 'Arcos de la Frontera',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'San Isidro Xtreme 2026',
    fecha: '2 May 2026',
    fecha_iso: '2026-05-02',
    ubicacion: 'La Puebla de Almoradiel, Toledo',
    municipio: 'La Puebla de Almoradiel',
    provincia: 'Toledo',
    comunidad: 'Castilla-La Mancha',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío Pinar Extremo 2026',
    fecha: '3 May 2026',
    fecha_iso: '2026-05-03',
    ubicacion: 'San Roque, Cádiz',
    municipio: 'San Roque',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Spartan Race Madrid Sprint 2026',
    fecha: '9 May 2026',
    fecha_iso: '2026-05-09',
    ubicacion: 'San Agustín del Guadalix, Madrid',
    municipio: 'San Agustín del Guadalix',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'OCR',
    modalidad_id: 'ocr-spartan',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://es.spartan.com/es/races/find-a-race',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Rabiosa Race Marcilla 2026',
    fecha: '9 May 2026',
    fecha_iso: '2026-05-09',
    ubicacion: 'Marcilla, Navarra',
    municipio: 'Marcilla',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Cavernícola Race Barbadás 2026',
    fecha: '9 May 2026',
    fecha_iso: '2026-05-09',
    ubicacion: 'Barbadás, Ourense',
    municipio: 'Barbadás',
    provincia: 'Ourense',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Estorbo Race Zaragoza 2026',
    fecha: '9 May 2026',
    fecha_iso: '2026-05-09',
    ubicacion: 'La Cartuja Baja, Zaragoza',
    municipio: 'La Cartuja Baja',
    provincia: 'Zaragoza',
    comunidad: 'Aragón',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Salvando Race Córdoba 2026',
    fecha: '10 May 2026',
    fecha_iso: '2026-05-10',
    ubicacion: 'Villanueva de Córdoba, Córdoba',
    municipio: 'Villanueva de Córdoba',
    provincia: 'Córdoba',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Crazy Run Archena 2026',
    fecha: '10 May 2026',
    fecha_iso: '2026-05-10',
    ubicacion: 'Archena, Murcia',
    municipio: 'Archena',
    provincia: 'Murcia',
    comunidad: 'Región de Murcia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Edelweiss Race Sabiñánigo 2026',
    fecha: '10 May 2026',
    fecha_iso: '2026-05-10',
    ubicacion: 'Sabiñánigo, Huesca',
    municipio: 'Sabiñánigo',
    provincia: 'Huesca',
    comunidad: 'Aragón',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Poseidon Race Cerceda 2026',
    fecha: '16 May 2026',
    fecha_iso: '2026-05-16',
    ubicacion: 'Cerceda, A Coruña',
    municipio: 'Cerceda',
    provincia: 'A Coruña',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Survivor Race Barcelona 2026',
    fecha: '16 May 2026',
    fecha_iso: '2026-05-16',
    ubicacion: 'Barcelona',
    municipio: 'Barcelona',
    provincia: 'Barcelona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://survivor-race.com/carreras/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Isla Race Port Adriano 2026',
    fecha: '17 May 2026',
    fecha_iso: '2026-05-17',
    ubicacion: 'Port Adriano, Islas Baleares',
    municipio: 'Port Adriano',
    provincia: 'Islas Baleares',
    comunidad: 'Islas Baleares',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Calvarian Race Alcorisa 2026',
    fecha: '23 May 2026',
    fecha_iso: '2026-05-23',
    ubicacion: 'Alcorisa, Teruel',
    municipio: 'Alcorisa',
    provincia: 'Teruel',
    comunidad: 'Aragón',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío Costa Blanca Mutxamel Mayo 2026',
    fecha: '24 May 2026',
    fecha_iso: '2026-05-24',
    ubicacion: 'Mutxamel, Alicante',
    municipio: 'Mutxamel',
    provincia: 'Alicante',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío de Guerreros Pineda de Mar 2026',
    fecha: '24 May 2026',
    fecha_iso: '2026-05-24',
    ubicacion: 'Pineda de Mar, Barcelona',
    municipio: 'Pineda de Mar',
    provincia: 'Barcelona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Denontzat Race Irún 2026',
    fecha: '29 May 2026',
    fecha_iso: '2026-05-29',
    ubicacion: 'Irún, Gipuzkoa',
    municipio: 'Irún',
    provincia: 'Gipuzkoa',
    comunidad: 'País Vasco',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Fan-Pin Race San Fernando 2026',
    fecha: '30 May 2026',
    fecha_iso: '2026-05-30',
    ubicacion: 'San Fernando, Cádiz',
    municipio: 'San Fernando',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Rural Warrior Tobarra 2026',
    fecha: '30 May 2026',
    fecha_iso: '2026-05-30',
    ubicacion: 'Tobarra, Albacete',
    municipio: 'Tobarra',
    provincia: 'Albacete',
    comunidad: 'Castilla-La Mancha',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Faraon Race Buñuel 2026',
    fecha: '30 May 2026',
    fecha_iso: '2026-05-30',
    ubicacion: 'Buñuel, Navarra',
    municipio: 'Buñuel',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── JUNIO 2026 ─────────────────────────────────────────────
  {
    nombre: 'Desafío Arcilasis 2026',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'Archivel, Murcia',
    municipio: 'Archivel',
    provincia: 'Murcia',
    comunidad: 'Región de Murcia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Survivor Race Madrid 2026',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'Madrid',
    municipio: 'Madrid',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://survivor-race.com/carreras/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Gladiator Race Pontevedra 2026',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'Pontevedra',
    municipio: 'Pontevedra',
    provincia: 'Pontevedra',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Pinatarius Obstaculum Cursus 2026',
    fecha: '6 Jun 2026',
    fecha_iso: '2026-06-06',
    ubicacion: 'San Pedro del Pinatar, Murcia',
    municipio: 'San Pedro del Pinatar',
    provincia: 'Murcia',
    comunidad: 'Región de Murcia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Medieval Xtreme Race Alginet 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'Alginet, Valencia',
    municipio: 'Alginet',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Wolf Race Caparroso 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'Caparroso, Navarra',
    municipio: 'Caparroso',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Legion Race Manresa 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'Manresa, Barcelona',
    municipio: 'Manresa',
    provincia: 'Barcelona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Unbroken Race Onda 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'Onda, Castellón',
    municipio: 'Onda',
    provincia: 'Castellón',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'OCR Mencey La Gomera 2026',
    fecha: '13 Jun 2026',
    fecha_iso: '2026-06-13',
    ubicacion: 'La Gomera, Tenerife',
    municipio: 'La Gomera',
    provincia: 'Santa Cruz de Tenerife',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'A Revolta Irmandiña 2026',
    fecha: '14 Jun 2026',
    fecha_iso: '2026-06-14',
    ubicacion: 'Verín, Ourense',
    municipio: 'Verín',
    provincia: 'Ourense',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Argoños OCR 2026',
    fecha: '14 Jun 2026',
    fecha_iso: '2026-06-14',
    ubicacion: 'Argoños, Cantabria',
    municipio: 'Argoños',
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Hard Running Valdetorres de Jarama 2026',
    fecha: '14 Jun 2026',
    fecha_iso: '2026-06-14',
    ubicacion: 'Valdetorres de Jarama, Madrid',
    municipio: 'Valdetorres de Jarama',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Samoa Race Granada 2026',
    fecha: '20 Jun 2026',
    fecha_iso: '2026-06-20',
    ubicacion: 'Cogollos de la Vega, Granada',
    municipio: 'Cogollos de la Vega',
    provincia: 'Granada',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Othar Race Cózar 2026',
    fecha: '20 Jun 2026',
    fecha_iso: '2026-06-20',
    ubicacion: 'Cózar, Ciudad Real',
    municipio: 'Cózar',
    provincia: 'Ciudad Real',
    comunidad: 'Castilla-La Mancha',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Heracles Race Caldes de Malavella 2026',
    fecha: '20 Jun 2026',
    fecha_iso: '2026-06-20',
    ubicacion: 'Caldes de Malavella, Girona',
    municipio: 'Caldes de Malavella',
    provincia: 'Girona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Carrera de Combate Valladolid 2026',
    fecha: '20 Jun 2026',
    fecha_iso: '2026-06-20',
    ubicacion: 'Santovenia de Pisuerga, Valladolid',
    municipio: 'Santovenia de Pisuerga',
    provincia: 'Valladolid',
    comunidad: 'Castilla y León',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío de Guerreros Valencia Jun 2026',
    fecha: '21 Jun 2026',
    fecha_iso: '2026-06-21',
    ubicacion: 'Valencia',
    municipio: 'Valencia',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Aguila Race Aguilafuente 2026',
    fecha: '21 Jun 2026',
    fecha_iso: '2026-06-21',
    ubicacion: 'Aguilafuente, Segovia',
    municipio: 'Aguilafuente',
    provincia: 'Segovia',
    comunidad: 'Castilla y León',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Invader Race Alt Penedès 2026',
    fecha: '27 Jun 2026',
    fecha_iso: '2026-06-27',
    ubicacion: 'Alt Penedès, Barcelona',
    municipio: 'Alt Penedès',
    provincia: 'Barcelona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Zufarian Race Zuera 2026',
    fecha: '27 Jun 2026',
    fecha_iso: '2026-06-27',
    ubicacion: 'Zuera, Zaragoza',
    municipio: 'Zuera',
    provincia: 'Zaragoza',
    comunidad: 'Aragón',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Heroican Race Ribadeo 2026',
    fecha: '28 Jun 2026',
    fecha_iso: '2026-06-28',
    ubicacion: 'Ribadeo, Lugo',
    municipio: 'Ribadeo',
    provincia: 'Lugo',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── JULIO 2026 ─────────────────────────────────────────────
  {
    nombre: 'Desafio Ilurcis Alfaro 2026',
    fecha: '4 Jul 2026',
    fecha_iso: '2026-07-04',
    ubicacion: 'Alfaro, La Rioja',
    municipio: 'Alfaro',
    provincia: 'La Rioja',
    comunidad: 'La Rioja',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Samurai Xtreme Race As Pontes 2026',
    fecha: '4 Jul 2026',
    fecha_iso: '2026-07-04',
    ubicacion: 'As Pontes de García Rodríguez, A Coruña',
    municipio: 'As Pontes de García Rodríguez',
    provincia: 'A Coruña',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desembarco Vikingo Colindres 2026',
    fecha: '11 Jul 2026',
    fecha_iso: '2026-07-11',
    ubicacion: 'Colindres, Cantabria',
    municipio: 'Colindres',
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── AGOSTO 2026 ────────────────────────────────────────────
  {
    nombre: 'Desafio Cantabro Viérnoles 2026',
    fecha: '1 Ago 2026',
    fecha_iso: '2026-08-01',
    ubicacion: 'Viérnoles, Cantabria',
    municipio: 'Viérnoles',
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Xtreme Natural Tesorillo 2026',
    fecha: '2 Ago 2026',
    fecha_iso: '2026-08-02',
    ubicacion: 'San Martín del Tesorillo, Cádiz',
    municipio: 'San Martín del Tesorillo',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Patuntos Race Ahigal de los Aceiteros 2026',
    fecha: '15 Ago 2026',
    fecha_iso: '2026-08-15',
    ubicacion: 'Ahigal de los Aceiteros, Salamanca',
    municipio: 'Ahigal de los Aceiteros',
    provincia: 'Salamanca',
    comunidad: 'Castilla y León',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── SEPTIEMBRE 2026 ────────────────────────────────────────
  {
    nombre: 'Desafio Cantabro Noja 2026',
    fecha: '6 Sep 2026',
    fecha_iso: '2026-09-06',
    ubicacion: 'Noja, Cantabria',
    municipio: 'Noja',
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Lobo Race Salas 2026',
    fecha: '6 Sep 2026',
    fecha_iso: '2026-09-06',
    ubicacion: 'Salas, Asturias',
    municipio: 'Salas',
    provincia: 'Asturias',
    comunidad: 'Principado de Asturias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Victoria Race Nanclares de la Oca 2026',
    fecha: '12 Sep 2026',
    fecha_iso: '2026-09-12',
    ubicacion: 'Nanclares de la Oca, Álava',
    municipio: 'Nanclares de la Oca',
    provincia: 'Álava',
    comunidad: 'País Vasco',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Kong Race Calonge 2026',
    fecha: '12 Sep 2026',
    fecha_iso: '2026-09-12',
    ubicacion: 'Calonge, Girona',
    municipio: 'Calonge',
    provincia: 'Girona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Uros Race Toén 2026',
    fecha: '13 Sep 2026',
    fecha_iso: '2026-09-13',
    ubicacion: 'Toén, Ourense',
    municipio: 'Toén',
    provincia: 'Ourense',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío Costa Blanca Bigastro Sep 2026',
    fecha: '13 Sep 2026',
    fecha_iso: '2026-09-13',
    ubicacion: 'Bigastro, Alicante',
    municipio: 'Bigastro',
    provincia: 'Alicante',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Iberus Race Milagro 2026',
    fecha: '19 Sep 2026',
    fecha_iso: '2026-09-19',
    ubicacion: 'Milagro, Navarra',
    municipio: 'Milagro',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Salvaje Race San Fernando 2026',
    fecha: '19 Sep 2026',
    fecha_iso: '2026-09-19',
    ubicacion: 'San Fernando, Cádiz',
    municipio: 'San Fernando',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Atlantis Race Carballo 2026',
    fecha: '19 Sep 2026',
    fecha_iso: '2026-09-19',
    ubicacion: 'Carballo, A Coruña',
    municipio: 'Carballo',
    provincia: 'A Coruña',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Adrenaline Race Zahara de los Atunes 2026',
    fecha: '26 Sep 2026',
    fecha_iso: '2026-09-26',
    ubicacion: 'Zahara de los Atunes, Cádiz',
    municipio: 'Zahara de los Atunes',
    provincia: 'Cádiz',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Valkiria Race Barreiros 2026',
    fecha: '26 Sep 2026',
    fecha_iso: '2026-09-26',
    ubicacion: 'Barreiros, Lugo',
    municipio: 'Barreiros',
    provincia: 'Lugo',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Pirates Race Bétera 2026',
    fecha: '26 Sep 2026',
    fecha_iso: '2026-09-26',
    ubicacion: 'Bétera, Valencia',
    municipio: 'Bétera',
    provincia: 'Valencia',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Santuario Race Malpartida de Cáceres 2026',
    fecha: '27 Sep 2026',
    fecha_iso: '2026-09-27',
    ubicacion: 'Malpartida de Cáceres, Cáceres',
    municipio: 'Malpartida de Cáceres',
    provincia: 'Cáceres',
    comunidad: 'Extremadura',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío de Guerreros Madrid Sep 2026',
    fecha: '27 Sep 2026',
    fecha_iso: '2026-09-27',
    ubicacion: 'Madrid',
    municipio: 'Madrid',
    provincia: 'Madrid',
    comunidad: 'Comunidad de Madrid',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── OCTUBRE 2026 ───────────────────────────────────────────
  {
    nombre: 'Lince Extreme Running Punta Umbría 2026',
    fecha: '3 Oct 2026',
    fecha_iso: '2026-10-03',
    ubicacion: 'Punta Umbría, Huelva',
    municipio: 'Punta Umbría',
    provincia: 'Huelva',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Valhalla Race L\'Alcora 2026',
    fecha: '3 Oct 2026',
    fecha_iso: '2026-10-03',
    ubicacion: "L'Alcora, Castellón",
    municipio: "L'Alcora",
    provincia: 'Castellón',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Hard Running La Carolina 2026',
    fecha: '4 Oct 2026',
    fecha_iso: '2026-10-04',
    ubicacion: 'La Carolina, Jaén',
    municipio: 'La Carolina',
    provincia: 'Jaén',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío Boot Camp Vigo 2026',
    fecha: '4 Oct 2026',
    fecha_iso: '2026-10-04',
    ubicacion: 'Vigo, Pontevedra',
    municipio: 'Vigo',
    provincia: 'Pontevedra',
    comunidad: 'Galicia',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'OCR Mencey La Laguna 2026',
    fecha: '10 Oct 2026',
    fecha_iso: '2026-10-10',
    ubicacion: 'La Laguna, Tenerife',
    municipio: 'La Laguna',
    provincia: 'Santa Cruz de Tenerife',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Invictus Race Santoña 2026',
    fecha: '11 Oct 2026',
    fecha_iso: '2026-10-11',
    ubicacion: 'Santoña, Cantabria',
    municipio: 'Santoña',
    provincia: 'Cantabria',
    comunidad: 'Cantabria',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Gladius Race Santacara 2026',
    fecha: '17 Oct 2026',
    fecha_iso: '2026-10-17',
    ubicacion: 'Santacara, Navarra',
    municipio: 'Santacara',
    provincia: 'Navarra',
    comunidad: 'Comunidad Foral de Navarra',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Spartan Race Barcelona Oct 2026',
    fecha: '17 Oct 2026',
    fecha_iso: '2026-10-17',
    ubicacion: 'Santa Susana, Barcelona',
    municipio: 'Santa Susana',
    provincia: 'Barcelona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-spartan',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://es.spartan.com/es/races/find-a-race',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío de Guerreros Málaga 2026',
    fecha: '25 Oct 2026',
    fecha_iso: '2026-10-25',
    ubicacion: 'Rincón de la Victoria, Málaga',
    municipio: 'Rincón de la Victoria',
    provincia: 'Málaga',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Medieval Xtreme Race Peñíscola 2026',
    fecha: '25 Oct 2026',
    fecha_iso: '2026-10-25',
    ubicacion: 'Peñíscola, Castellón',
    municipio: 'Peñíscola',
    provincia: 'Castellón',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── NOVIEMBRE 2026 ─────────────────────────────────────────
  {
    nombre: 'OCR Mencey Los Realejos 2026',
    fecha: '8 Nov 2026',
    fecha_iso: '2026-11-08',
    ubicacion: 'Los Realejos, Tenerife',
    municipio: 'Los Realejos',
    provincia: 'Santa Cruz de Tenerife',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Gollizno Race Olivares 2026',
    fecha: '8 Nov 2026',
    fecha_iso: '2026-11-08',
    ubicacion: 'Olivares, Granada',
    municipio: 'Olivares',
    provincia: 'Granada',
    comunidad: 'Andalucía',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Monster Race Sant Miquel de Campmajor 2026',
    fecha: '8 Nov 2026',
    fecha_iso: '2026-11-08',
    ubicacion: 'Sant Miquel de Campmajor, Girona',
    municipio: 'Sant Miquel de Campmajor',
    provincia: 'Girona',
    comunidad: 'Cataluña',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Desafío Costa Blanca Mutxamel Nov 2026',
    fecha: '22 Nov 2026',
    fecha_iso: '2026-11-22',
    ubicacion: 'Mutxamel, Alicante',
    municipio: 'Mutxamel',
    provincia: 'Alicante',
    comunidad: 'Comunidad Valenciana',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
  {
    nombre: 'Spartan Race Tenerife Nov 2026',
    fecha: '28 Nov 2026',
    fecha_iso: '2026-11-28',
    ubicacion: 'Santa Cruz de Tenerife',
    municipio: 'Santa Cruz de Tenerife',
    provincia: 'Santa Cruz de Tenerife',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-spartan',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://es.spartan.com/es/races/find-a-race',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },

  // ── DICIEMBRE 2026 ─────────────────────────────────────────
  {
    nombre: 'Bestial Race Arucas 2026',
    fecha: '5 Dic 2026',
    fecha_iso: '2026-12-05',
    ubicacion: 'Arucas, Gran Canaria',
    municipio: 'Arucas',
    provincia: 'Las Palmas',
    comunidad: 'Canarias',
    modalidad: 'OCR',
    modalidad_id: 'ocr-general',
    modalidad_parent: 'ocr',
    distancia: null,
    precio: null,
    estado: 'Abierta',
    url: 'https://calendariocarrerasobstaculos.es/',
    formato: null,
    notas: null,
    source: 'calendariocarrerasobstaculos.es',
  },
];

// ── Detectar columnas disponibles en la tabla ────────────────────────────────
async function getAvailableColumns() {
  const { data, error } = await supabase.from('races').select('*').limit(1);
  if (error) {
    // Si la tabla está vacía el error es diferente; intentamos con select de columnas conocidas
    return new Set(['id','nombre','modalidad','modalidad_id','fecha','fecha_iso',
      'ubicacion','comunidad','pais','distancia','precio','estado','notas','url',
      'created_at','modalidad_parent']);
  }
  if (data.length > 0) return new Set(Object.keys(data[0]));
  // Tabla vacía: hacemos insert vacío para detectar columnas disponibles
  return new Set(['id','nombre','modalidad','modalidad_id','fecha','fecha_iso',
    'ubicacion','comunidad','pais','distancia','precio','estado','notas','url',
    'created_at','modalidad_parent']);
}

// ── Lógica de inserción ──────────────────────────────────────────────────────
async function upsertEvents() {
  const stats = {
    bySource: {},
    inserted: 0,
    updated: 0,
    skipped: 0,
    errors: [],
  };

  const availableCols = await getAvailableColumns();
  const hasCol = (c) => availableCols.has(c);

  console.log(`\n🚀 Iniciando inserción de ${EVENTS.length} eventos en Supabase...`);
  console.log(`   Columnas disponibles: ${[...availableCols].filter(c => c !== 'id' && c !== 'created_at').join(', ')}\n`);

  for (const ev of EVENTS) {
    const source = ev.source || 'unknown';
    stats.bySource[source] = (stats.bySource[source] || 0) + 1;

    // Base payload con columnas siempre presentes
    const payload = {
      nombre: ev.nombre,
      fecha: ev.fecha ?? null,
      fecha_iso: ev.fecha_iso ?? null,
      ubicacion: ev.ubicacion ?? null,
      comunidad: ev.comunidad ?? null,
      pais: 'España',
      modalidad: ev.modalidad ?? null,
      modalidad_id: ev.modalidad_id ?? null,
      modalidad_parent: ev.modalidad_parent ?? null,
      distancia: ev.distancia ?? null,
      precio: ev.precio ?? null,
      estado: ev.estado ?? 'Abierta',
      url: ev.url ?? null,
      notas: ev.notas ? ev.notas.substring(0, 100) : null,
    };

    // Columnas opcionales — solo si existen en la BD
    if (hasCol('municipio'))   payload.municipio   = ev.municipio ?? null;
    if (hasCol('provincia'))   payload.provincia   = ev.provincia ?? null;
    if (hasCol('formato'))     payload.formato     = ev.formato ?? null;
    if (hasCol('source'))      payload.source      = ev.source ?? null;
    if (hasCol('distancia_km') && ev.distancia_km != null)
      payload.distancia_km = ev.distancia_km;

    try {
      // Buscar si ya existe por nombre + fecha_iso
      const { data: existing } = await supabase
        .from('races')
        .select('id, precio, estado')
        .eq('nombre', payload.nombre)
        .eq('fecha_iso', payload.fecha_iso ?? '')
        .maybeSingle();

      if (existing) {
        // Actualizar precio y estado
        const { error } = await supabase
          .from('races')
          .update({ precio: payload.precio, estado: payload.estado, url: payload.url })
          .eq('id', existing.id);

        if (error) throw error;
        stats.updated++;
        console.log(`  ↻  ACTUALIZADO: ${payload.nombre}`);
      } else {
        const { error } = await supabase.from('races').insert(payload);
        if (error) throw error;
        stats.inserted++;
        console.log(`  ✓  INSERTADO:   ${payload.nombre}`);
      }
    } catch (err) {
      stats.errors.push({ nombre: payload.nombre, error: err.message });
      console.error(`  ✗  ERROR:       ${payload.nombre} — ${err.message}`);
    }
  }

  return stats;
}

// ── Informe final ─────────────────────────────────────────────────────────────
async function printReport(stats) {
  // Obtener todos los eventos de Supabase ordenados por fecha
  const { data: allEvents, error } = await supabase
    .from('races')
    .select('nombre, fecha_iso, comunidad, modalidad, estado')
    .order('fecha_iso', { ascending: true, nullsFirst: false });

  console.log('\n' + '═'.repeat(60));
  console.log('INFORME FINAL');
  console.log('═'.repeat(60));

  console.log('\n📊 EVENTOS POR FUENTE:');
  for (const [src, count] of Object.entries(stats.bySource)) {
    console.log(`   ${src.padEnd(40)} ${count} eventos`);
  }

  console.log(`\n✅ Insertados:  ${stats.inserted}`);
  console.log(`↻  Actualizados: ${stats.updated}`);
  console.log(`⚠  Errores:     ${stats.errors.length}`);

  if (stats.errors.length > 0) {
    console.log('\n❌ ERRORES DETALLADOS:');
    for (const e of stats.errors) {
      console.log(`   • ${e.nombre}: ${e.error}`);
    }
  }

  if (allEvents) {
    console.log(`\n📋 TODOS LOS EVENTOS EN BD (${allEvents.length} total, ordenados por fecha):`);
    console.log('─'.repeat(60));
    for (const ev of allEvents) {
      const fecha = ev.fecha_iso ?? '(sin fecha)';
      const estado = ev.estado?.padEnd(12) ?? ''.padEnd(12);
      console.log(`  ${fecha}  ${estado}  ${ev.nombre}`);
    }
  }

  console.log('\n' + '═'.repeat(60));
}

// ── Main ──────────────────────────────────────────────────────────────────────
const stats = await upsertEvents();
await printReport(stats);
